### PR TITLE
Add Save/Load State to All.cfg

### PR DESCRIPTION
**Pull request by nicholaus12**
Forgot to add Save/Load State to All.cfg and changed retrogame.cfg so that Mute passes the same value as Select. This allows you to use either Mute or Select as the hotkey and maintains Home as the shortcut for exiting games.

### CODE REVIEW

**Review by nicholaus12 — COMMENTED** [review]
Wasn't thinking and realized my changes in retrogame didn't fix the problem of using Mute as hotkey since it was the same as pressing Select.

**Comment by othermod** [comment]
Should be able to do that, and set the Select and Mute buttons to do the same thing. I'm not sure that I want to make it the default for everyone though.

I removed all.cfg from the repository. It was an earlier version of the retroarch.cfg file and isn't used at all.

**Comment by nicholaus12** [comment]
I realized setting Mute to the same as Select, “D” in retrogame, didn’t actually solve anything for me. It still executed the “Select” button action in games, it just made two physical buttons that did the exact same thing next to one another, which is pointless and a waste of a button. I went back to what I was doing first which was setting up Mute as “G” in retrogame and changing input_enable_hotkey in retroarch to “g” as well. This made the Mute key the hotkey, but Home would no longer exit the game. Mute and Start exits the game, but I use Mute and Home because Home still does the Start action and I can use both thumbs instead of changing up my grip to hit Mute and Start with the one hand.

**Comment by nicholaus12** [comment]
I think I need to edit a file to capture the Home button event by checking if both S and D are pressed at same time and changing it to S and Mute (G in my case). That’s the only thing I can think of right now since it’s hardwired that way and not in software.

**Comment by othermod** [comment]
I agree. I'm not sure what needs to be changed in retroarch to make that work, but it seems doable.

**Pull request closed without merging**
